### ISSUE TITLE
Label file format

### ISSUE THREAD

**Issue by felipecpc** [chuanenlin/drone-net#4]
Quick question for the label files. 

At yolo doc it says:
<object-class> <x> <y> <width> <height>
_Where x, y, width, and height are relative to the image's width and height._

In your label files you have the real coordinates (x,y for the center of the image) and width/height, is that correct?

**Comment by chuanenlin** [comment]
That is correct. :)

**Comment by felipecpc** [comment]
Got it ! So what is on the readme is not true:
_The original and labeled images used for retraining can be found under the image and label folders respectively._

Before training it is needed to do the conversion, like you said on ```format.py```
I'll try it myself :)

One question, how long does it take to train the network ?

**Comment by chuanenlin** [comment]
The labels in the repo are already in YOLO format so they can be used for training directly. I see that you came from my Medium post where we used BBox annotator for labeling in Mechanical Turk - in that case, you may convert your BBox annotator labels using `format.py` yes.

The weights in this repo was trained for about three days on a NVIDIA Tesla from [darknet53.conv.74](https://pjreddie.com/media/files/darknet53.conv.74) and you may use the weights to continue training from where I left off.
