### ISSUE TITLE
Train Darknet

### ISSUE THREAD

**Issue by aravind93raja** [chuanenlin/drone-net#7]
When i run darknet to train my custom set of images  ,

I get the following error

darknet: ./src/parser.c:315: parse_yolo: Assertion `l.outputs == params.inputs' failed.
Aborted (core dumped)

**Comment by chuanenlin** [comment]
Can you check if your filter value(s) in the convolution layer(s) follow (classes + 5) * 3? [This](https://github.com/pjreddie/darknet/issues/236) might be useful.

**Comment by cvramanan** [comment]
I too have the same error , i have tried all the remedies given above but still the error occurs. Have anyone fixed the error
